spring:
  application:
    name: mealplanner

  datasource:
    url: jdbc:postgresql://localhost:5432/meal_planner_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update